name: base
channels:
  - local
  - conda-forge
dependencies:
  - pip=21.1.2=pyhd8ed1ab_0
  - tensorboardx=2.2=pyhd8ed1ab_0
  - pip:
    - atari-py==0.2.9
    - cloudpickle==1.6.0
    - gym==0.18.3
    - opencv-python==4.5.3.56
    - pillow==8.2.0
    - pyglet==1.5.15
